### ISSUE TITLE
Not getting IP 

### ISSUE THREAD

**Issue by lukaspavelka** [Todd1561/TANIPChecker#1]
Hi i just try you tool on my 2 machines and both have some issue. Not getting any info, mail will come but no IP in it... 

How i run tool:
![Screenshot 2024-05-13 105539](https://github.com/Todd1561/TANIPChecker/assets/48788338/f2cc9d32-3ee0-40cc-a7f3-d0b9f31182e9)

i receive 2 emails like this: 

1) First mail: 
The request was aborted: Could not create SSL/TLS secure channel.

at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
at System.Net.WebClient.DownloadString(Uri address)
at System.Net.WebClient.DownloadString(String address)
at TANIPChecker.Module1.GetIP()

2) Second mail: 

![image](https://github.com/Todd1561/TANIPChecker/assets/48788338/fa75d7a7-882d-4dd8-8275-5e1b463840c8)

**Comment by Todd1561** [comment]
What OS are you using? Seems like your system is having trouble accessing the IP web service I use for this app.  Try going to https://api.ipify.org/ in a browser and see what it returns.  It should just be your IP address in plain text.

If that doesn't work try going to the same site under just http and see if that works.  It seems like they offer both so I could switch to just http and avoid the SSL issue altogether I suppose.

**Comment by lukaspavelka** [comment]
Hi it is Windows 10 Pro, 2 PC on different network , one from office , one from home. 

For browser it looks like working: 

![image](https://github.com/Todd1561/TANIPChecker/assets/48788338/e2eccc26-230c-4555-a0f1-1c18e98f5e33)

**Comment by Todd1561** [comment]
Sorry my bad, I fixed this problem a couple years ago by switching to .Net Framework 4.8 but apparently I never published a new release .exe.  I just now published version 1.10 that should fix this, let me know.

**Comment by lukaspavelka** [comment]
hehe nice all working well now :) Thx

**Comment by Todd1561** [comment]
Great, thanks.

**Comment by lukaspavelka** [comment]
would by very nice if there is also parameter for change email subject so can i add info from what server/client i get ip changed  ... just idea :)

**Comment by Todd1561** [comment]
Sure, I just published release 1.20 which can do this.  Use quotes when specifying the text. e.g. 
`/subject="Home IP Address Changed"`

**Comment by lukaspavelka** [comment]
Wau man i am speechless , you are king! Thanks for great work.
